version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    # restart: unless-stopped
    ports:
      - 3500:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    image: brandexio/node-app:latest
    container_name: node-app
    # restart: unless-stopped
    working_dir: /app
    environment:
      - PORT=3000
    env_file:
      - ./.env
    depends_on:
      - mongo
      
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  redis:
    image: redis

volumes:
  mongo-db:
     