version: '3'
services:
  node-app:
    build: .
    container_name: node-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app:ro
      - /app/node_modules
    command: npm run dev
    ports:
      - 3500:3000
    environment:
      - PORT=3000
    env_file:
      - ./.env